#API for creating account for user
###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "username":"django",
    "email":"django@gmail.com",
    "password":"django"
}


#Api for create a new post
###
POST http://127.0.0.1:8000/api/posts/
Authorization: Basic django:django
Content-Type: application/json

{
    "title":"ga",
    "description":"good afternoon"
}

# API for list all posts
###
GET http://127.0.0.1:8000/api/posts/
Authorization: Basic django:django

# API for fetching post detail
###
GET http://127.0.0.1:8000/api/posts/1/
Authorization: Basic django:django


# Api for updating a post
###
PUT  http://127.0.0.1:8000/api/posts/3/
Authorization: Basic django:django
Content-Type: application/json

{
  
  "title": "gn",
  "description": "good night"
 
}


# Api for deleting a post
###
DELETE  http://127.0.0.1:8000/api/posts/3/
Authorization: Basic django:django


# api call for adding a comment for a post
###
POST http://127.0.0.1:8000/api/posts/2/comments/
Content-Type: application/json
Authorization: Basic django:django

{
  "message":"hello"
}







